// Built-in game content. Couples never need to search the web for questions (§5).
// All prompts are couple-friendly and non-explicit.
// {p} = the partner being asked about (filled in at runtime).

const wouldYouRather = <List<String>>[
  ['Have a picnic under the stars', 'Have breakfast in bed'],
  ['Get a surprise letter every week', 'Get a surprise visit once a year'],
  ['Only video call forever', 'Only voice call forever'],
  ['Travel the world together for a year', 'Have your dream home together'],
  ['Always know what I\'m thinking', 'Never be able to surprise me'],
  ['Cook together every night', 'Dance together every night'],
  ['Relive our first date', 'Skip ahead to see us in 10 years'],
  ['Have matching tattoos', 'Have matching pyjamas forever'],
  ['Be stuck in a lift with me for 6 hours', 'Not see me for 6 days'],
  ['Write me a song', 'Write me a 10-page letter'],
  ['Have a cosy cabin weekend', 'Have a city-lights weekend'],
  ['Laugh at every joke I make', 'Have me laugh at every joke you make'],
  ['Go on a road trip with no plan', 'Go on a trip planned to the minute'],
  ['Watch only rom-coms together', 'Watch only horror together'],
  ['Have a pet together right now', 'Plant a garden together right now'],
  ['Receive flowers', 'Receive food'],
  ['Have our first kiss again', 'Have our first fight again — but win it'],
  ['Spend a day in each other\'s shoes', 'Spend a day reading each other\'s minds'],
  ['Get a slow dance in the kitchen', 'Get a serenade on a balcony'],
  ['Move to a new city together', 'Stay close to family together'],
  ['Have a 3-hour phone call', 'Have 30 short texts throughout the day'],
  ['Be famous as a couple', 'Be secretly legendary to our friends'],
  ['Always win at games against me', 'Always have me cheer for you'],
  ['Sunrise together', 'Sunset together'],
  ['Learn a language together', 'Learn an instrument together'],
];

const thisOrThat = <List<String>>[
  ['Coffee ☕', 'Tea 🍵'], ['Beach 🏖️', 'Mountains 🏔️'], ['Night owl 🦉', 'Early bird 🐦'],
  ['Pizza 🍕', 'Jollof 🍛'], ['Movies 🎬', 'Series 📺'], ['Texting 💬', 'Calling 📞'],
  ['Cats 🐱', 'Dogs 🐶'], ['Sweet 🍰', 'Savoury 🍟'], ['Rain 🌧️', 'Sunshine ☀️'],
  ['Books 📚', 'Podcasts 🎧'], ['Big party 🎉', 'Small dinner 🍷'], ['City 🌆', 'Countryside 🌾'],
  ['Cuddles 🤗', 'Kisses 😘'], ['Plan it 🗓️', 'Wing it 🎲'], ['Spicy 🌶️', 'Mild 🥛'],
  ['Summer ☀️', 'Winter ❄️'], ['Gym 🏋️', 'Nap 😴'], ['Morning texts 🌅', 'Goodnight texts 🌙'],
  ['Surprise gifts 🎁', 'Chosen gifts 🛍️'], ['Dance 💃', 'Sing 🎤'], ['Sneakers 👟', 'Sandals 🩴'],
  ['Comedy 😂', 'Thriller 😱'], ['Cooking 🍳', 'Ordering in 🛵'], ['Old songs 📻', 'New songs 🎶'],
  ['Window seat 🪟', 'Aisle seat 🚶'],
];

const neverHaveIEver = <String>[
  'Never have I ever pretended to be asleep to avoid a call.',
  'Never have I ever re-read our old messages.',
  'Never have I ever practised what to say before calling you.',
  'Never have I ever laughed so hard I cried on a call with you.',
  'Never have I ever stalked your old photos.',
  'Never have I ever told a friend about you within a day of meeting you.',
  'Never have I ever fallen asleep on a call.',
  'Never have I ever lied about liking a gift.',
  'Never have I ever sung in the shower thinking of you.',
  'Never have I ever forgotten an important date.',
  'Never have I ever cried at a movie.',
  'Never have I ever been jealous of your friend.',
  'Never have I ever had a dream about you.',
  'Never have I ever eaten something you left for later.',
  'Never have I ever planned our future in my head.',
  'Never have I ever screenshotted one of your messages to show someone.',
  'Never have I ever sent a message and immediately regretted it.',
  'Never have I ever been nervous before seeing you.',
  'Never have I ever googled something you said to sound smart.',
  'Never have I ever written your name somewhere just because.',
  'Never have I ever pretended to know a song you love.',
  'Never have I ever got lost on the way to meet you.',
  'Never have I ever wished I could pause time when we were together.',
  'Never have I ever kept something of yours on purpose.',
];

const deepQuestions = <String>[
  'What\'s a moment with me you replay in your head?',
  'When do you feel most loved by me?',
  'What\'s something you\'ve never told me but want to?',
  'What does "home" mean to you now?',
  'What\'s one dream you\'d like us to chase together?',
  'What part of our relationship are you most proud of?',
  'What\'s a fear you have about the future, and how can I help with it?',
  'What did you think of me the first time we talked?',
  'What\'s something small I do that means a lot to you?',
  'How have you grown since we met?',
  'What\'s a tradition you\'d love for us to start?',
  'When was a time you felt really understood by me?',
  'What do you need more of from me right now?',
  'What does a perfect ordinary day with me look like?',
  'What\'s a lesson your family taught you about love?',
  'What would you want to remember about this year of us?',
  'What makes you feel safe to be completely yourself?',
  'What\'s a promise you want to make to me?',
  'If we wrote a book about us, what would chapter one be called?',
  'What\'s the bravest thing you\'ve done for love?',
  'What do you hope we\'re doing ten years from today?',
  'What\'s something hard we got through that made us stronger?',
];

const funnyQuestions = <String>[
  'If I were a kitchen appliance, which one would I be and why?',
  'What would my villain origin story be?',
  'What\'s the most ridiculous argument we could have?',
  'If we were a sitcom, what would it be called?',
  'Which cartoon character am I secretly most like?',
  'What would I be famous for in a small village?',
  'If I had a warning label, what would it say?',
  'What\'s my most suspicious habit?',
  'What would I do with one hour of being invisible?',
  'What food would I be banned from in 3 countries for eating weirdly?',
  'If our relationship had a theme song, what\'s playing right now?',
  'What would I name a pet goat?',
  'What would my autobiography be titled?',
  'What reality show would I accidentally win?',
  'What\'s the worst superpower I could realistically have?',
  'If I were a dessert, which one would I be?',
  'What would happen if I ran the country for one day?',
  'What would our couple\'s Instagram handle be?',
  'What\'s the most "me" thing I\'ve ever done?',
  'What would I bring to a desert island that makes no sense?',
  'If I opened a restaurant, what would go terribly wrong first?',
  'Describe me using only three emojis.',
];

const coupleQuiz = <String>[
  'Where did we first meet (or first talk)?',
  'What was the first thing we ever argued about?',
  'Who said "I love you" first?',
  'What was our first date (real or virtual)?',
  'Which song reminds us both of each other?',
  'What\'s our most-used inside joke?',
  'What\'s the longest we\'ve gone without talking?',
  'Who is the better cook?',
  'Who apologises first after a disagreement?',
  'What\'s our dream holiday destination together?',
  'Who is more likely to cry at a movie?',
  'What was the first gift we gave each other?',
  'Who fell first?',
  'What\'s our favourite thing to do together?',
  'What\'s a food we both hate?',
  'Who\'s funnier? (Be honest.)',
  'What\'s the best day we\'ve had together so far?',
  'What nickname do we use most for each other?',
];

const compatibility = <String>[
  'How much do you love surprises?',
  'How tidy do you need your space to be?',
  'How important is alone time to you?',
  'How adventurous are you with food?',
  'How much do you enjoy big social events?',
  'How important are traditions and holidays to you?',
  'How much do you like planning ahead?',
  'How much do you love physical affection?',
  'How competitive are you at games?',
  'How much do you enjoy trying new hobbies?',
  'How much do you value saving money over spending on fun?',
  'How early do you like to wake up?',
  'How much do you enjoy deep conversations late at night?',
  'How important is it to talk every single day?',
  'How spontaneous are you?',
  'How much do you enjoy staying in versus going out?',
];

/// "How Well Do You Know Me?" — subject answers about themselves, partner guesses (free text).
const knowMe = <String>[
  'What\'s {p}\'s go-to comfort food?',
  'What\'s {p}\'s biggest pet peeve?',
  'What would {p} do with a free Saturday?',
  'What\'s {p}\'s dream job (if money didn\'t matter)?',
  'What\'s {p}\'s favourite way to be cheered up?',
  'Which song would {p} play on repeat right now?',
  'What\'s {p} secretly really good at?',
  'What\'s the first thing {p} does in the morning?',
  'What would {p} order at a new restaurant?',
  'What scares {p} more than they admit?',
  'What\'s {p}\'s favourite memory from childhood?',
  'Who is {p}\'s celebrity crush?',
  'What\'s {p}\'s love language?',
  'Where in the world does {p} most want to go?',
  'What\'s {p}\'s guilty-pleasure show?',
  'What\'s {p}\'s most-used emoji?',
  'What\'s the best gift {p} has ever received?',
  'What would {p} grab first in a fire (people and pets are safe)?',
];

/// "Guess My Answer" — multiple choice: subject picks, partner predicts. Auto-scored.
const guessMyAnswer = <List<String>>[
  ['Perfect Friday night for {p}?', 'Out with friends', 'Movie at home', 'Fancy dinner', 'Asleep by 10'],
  ['{p}\'s ideal holiday?', 'Beach & rest', 'City exploring', 'Adventure & hiking', 'Staycation'],
  ['How does {p} handle stress?', 'Talk it out', 'Go quiet', 'Exercise', 'Eat something nice'],
  ['{p}\'s favourite kind of gift?', 'Something handmade', 'Experiences', 'Something practical', 'Surprise treats'],
  ['What would {p} rather skip forever?', 'Laundry', 'Dishes', 'Cooking', 'Grocery shopping'],
  ['{p}\'s superpower pick?', 'Teleportation', 'Invisibility', 'Mind reading', 'Time travel'],
  ['Best way to say sorry to {p}?', 'A sincere talk', 'Food', 'A hug', 'A letter'],
  ['{p}\'s favourite part of the day?', 'Early morning', 'Afternoon', 'Evening', 'Late night'],
  ['What does {p} notice first in a room?', 'The music', 'The people', 'The food', 'The decor'],
  ['Which pet suits {p} best?', 'Dog', 'Cat', 'Fish', 'No pets, thanks'],
  ['{p}\'s dream date?', 'Rooftop dinner', 'Picnic', 'Concert', 'Cooking at home'],
  ['How does {p} like to celebrate a win?', 'Party', 'Quiet treat', 'Tell everyone', 'Straight to the next goal'],
  ['{p}\'s texting style?', 'Long paragraphs', 'Rapid short texts', 'Voice notes', 'Emojis & memes'],
  ['On a rainy day, {p} is…', 'Under a blanket', 'Dancing in it', 'Baking something', 'Annoyed'],
];

const truths = <String>[
  'What\'s the most romantic thing you\'ve ever imagined us doing?',
  'What was your honest first impression of me?',
  'What\'s a habit of mine you secretly find adorable?',
  'What\'s the silliest thing you\'ve been jealous of?',
  'When did you realise you liked me?',
  'What\'s one thing you wish I did more often?',
  'What\'s your most embarrassing moment ever?',
  'What\'s a song that makes you think of me?',
  'What\'s something you\'ve pretended to like for me?',
  'If you could change one thing about our first date, what would it be?',
  'What\'s the nicest thing someone has said about us?',
  'What\'s a secret talent nobody knows about?',
  'What do you miss most about me when we\'re apart?',
  'What\'s the weirdest dream you\'ve had about us?',
  'What\'s a small moment with me you\'ll never forget?',
  'What compliment from me has stuck with you?',
  'What\'s one thing on your bucket list you\'ve never said out loud?',
  'What\'s something about you that you think I don\'t know?',
];

const dares = <String>[
  'Sing the chorus of our song — dramatically.',
  'Do your best impression of me for 20 seconds.',
  'Send me the 5th photo in your gallery (if it\'s safe!).',
  'Tell me three things you love about me in your most dramatic movie-trailer voice.',
  'Do a 15-second victory dance.',
  'Speak only in rhymes until your next turn.',
  'Show me the last thing you bought.',
  'Read your last sent text out loud in a news-anchor voice.',
  'Draw a portrait of me in 60 seconds and show it.',
  'Write a two-line love poem right now, out loud.',
  'Make up a secret handshake we can do on video.',
  'Give me a compliment in another language (or accent).',
  'Do your best runway walk across the room.',
  'Tell me a joke. If I don\'t laugh, tell another.',
  'Hold eye contact with me for 30 seconds without laughing.',
  'Show me your best "I\'m in love" face.',
  'Plan our next date in 30 seconds — out loud.',
  'Act out how we met with only gestures.',
];

const challenges = <String>[
  'Both find something blue in your room in 20 seconds. Slowest picks the next movie!',
  'Draw each other in 2 minutes without looking at the paper. Reveal together.',
  'Make the other laugh in under 30 seconds — no touching the screen!',
  'Each write a 4-line poem with the words "moon", "rice" and "forever".',
  'Name 10 things you love about each other, taking turns. First to pause loses.',
  'Make a "date night menu" using only what\'s in your kitchens right now.',
  'Recreate a famous movie scene together on video.',
  'Each choose a song for the other. Listen together and react.',
  'Play "20 questions" — guess the object your partner is thinking of.',
  'Write tomorrow\'s good-morning text for each other now — save it for later!',
  'Tell a story together, one sentence each, starting with "Once upon a time, two lovebirds…"',
  'Teach each other one thing in 5 minutes (a word, a dance step, a trick).',
  'Take a selfie making the exact same face. Compare and judge.',
  'Plan a dream day in a city neither of you has visited — budget: unlimited.',
  'Hum a song; the other has 3 guesses.',
];
